print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/samantashi/Downloads/HideAndShoot-Cat/HideAndShoot/Final Project/Assets/toygun.mb"`)
{		
	file -o "/Users/samantashi/Downloads/HideAndShoot-Cat/HideAndShoot/Final Project/Assets/toygun.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/samantashi/Downloads/HideAndShoot-Cat/HideAndShoot/Final Project/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/samantashi/Downloads/HideAndShoot-Cat/HideAndShoot/Final Project/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/samantashi/Downloads/HideAndShoot-Cat/HideAndShoot/Final Project/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
